package com.docusign.proserv.application.domain;

public enum BulkOperations {

	NOTIFICATIONCHANGES, ENVELOPEUPDATES, ENVELOPECOPY, ENVELOPERESUME, ENVELOPECREATE, ENVELOPECREATEASYNC,
	ENVELOPETEMPLATECREATEUSINGFILE;
}